config/routes.rb
Rails.application.routes.draw do
  root 'visitor#index'
  get 'show_project/:id' => 'visitor#show_project', as: :show_project
  resources :projects
  put 'contact_form' => 'visitor#contact_form', as: :contact_form
  devise_for :user

end

app/models/project.rb
class Project < ActiveRecord::Base
	mount_uploader :base_image, AvatarUploader
	mount_uploader :gif_image, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @projects = Project.all
  end

  def show
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :details, :base_image, :gif_image)
    end
end

app/controllers/visitor_controller.rb
class VisitorController < ApplicationController
	def index
		@projects = Project.all
	end

	def contact_form
		user = {
			full_name: params[:contact][:full_name],
			email: params[:contact][:email],
			body: params[:contact][:body]
		}
		if UserMailer.contact_form(user).deliver_now
			UserMailer.confirmation(user).deliver_now
			redirect_to root_path, notice: 'Email Sent!'
		else
			redirecto_to root_path, notice: 'Email NOT Sent!'
		end
	end

	def show_project
		puts "Params: #{params}"
		@project = Project.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YarsSite</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target=".navbar-collapse" data-offset="50">

  <%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :base_image %><br>
    <%= f.file_field :base_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<!-- navigation section -->
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon icon-bar"></span> <span class="icon icon-bar"></span> <span class="icon icon-bar"></span> </button>
      <a href="#" class="navbar-brand" style="margin-bottom:20px;font-size:25px;">Admin Portal</a></div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
      </ul>
    </div>
  </div>
</div>


<div id="projects-table">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 style="text-align:left;">Listing Projects</h1>
        <%= link_to 'New Project', new_project_path, class: 'btn btn-default', style: 'float:right;' %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Details</th>
              <th>&nbsp;</th>
              <th>&nbsp;</th>
              <th>&nbsp;</th>
            </tr>
          </thead>

          <tbody>
            <% @projects.each do |project| %>
              <tr>
                <td style="text-align:left;"><%= project.name %></td>
                <td style="text-align:left;"><%= project.details %></td>
                <td><%= link_to 'Show', project %></td>
                <td><%= link_to 'Edit', edit_project_path(project) %></td>
                <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>    
      </div>
    </div>
  </div>
</div>

<div id="portfolio">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 title">
        <h2>Portfolio</h2>
        <hr>
      </div>

      <div class="col-md-12 col-sm-12"></div>
      <% @projects.each do |p| %>
        <div class="col-md-3 col-sm-3 wow fadeIn" data-wow-delay="0.6s">
          <%= link_to(show_project_path(p)) do %>
            <%= image_tag("#{p.base_image}", class: 'project-image') %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Details:</strong>
  <%= @project.details %>
</p>

<p>
	<strong>Base Image</strong>
	<%= image_tag @project.base_image.thumb.url %>
</p>

<p>
<% @projects.each do |p| %>
	<%= link_to "#{p.name}", project_path(p) %>
<% end %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', root_path %>

app/views/visitor/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12" style="color:black;">
        <h2 class="wow fadeIn" data-wow-delay="0.9s">Follow Me</h2>
        <ul class="social-icon">
          <li>
          	<a target="_blank" href="https://dribbble.com/yarkukhtin" class="fa fa-dribbble wow bounceIn" data-wow-delay="0.9s"></a>
          </li>
          <li>
          	<a target="_blank" href="https://vimeo.com/yarkukhtin" class="fa fa-vimeo wow bounceIn" data-wow-delay="0.9s"></a>
          </li>
          <li>
          	<a target="_blank" href="https://ca.linkedin.com/in/yarkukhtin" class="fa fa-linkedin wow bounceIn" data-wow-delay="0.9s"></a>
          </li>
          <li>
          	<a target="_blank" href="https://www.instagram.com/yarkukhtin/" class="fa fa-instagram wow bounceIn" data-wow-delay="0.9s"></a>
          </li>
        </ul>
      </div>
      <div class="col-md-12 col-sm-12 copyright" style="color:black;">
        <p>Copyright © Yar Kukhtin 2016 
        <!-- | Template by <a target="_blank" rel="nofollow" href="http://www.templatemo.com/tm-469-impulse">Impulse Design</a> --></p>
      </div>
    </div>
  </div>
</footer>

app/views/visitor/_header.html.erb
<!-- preloader section -->
    <div class="preloader">
      <!-- <div class="sk-spinner sk-spinner-rotating-plane"></div> -->
      <div class="container">
        <span class="dots"></span>
        <span class="dots"></span>
        <span class="dots"></span>
        <span class="dots"></span>
        <span class="dots"></span>
        <span class="dots"></span>
        <span class="dots"></span>
        <span class="dots"></span>
        <span class="dots"></span>
        <span class="dots"></span>
      </div>
    </div>
    <a href="javascript:" id="return-to-top"><i class="fa fa-chevron-up"></i></a>
    <!-- home section -->
    <section id="home">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12">
            <%= image_tag 'https://s3.amazonaws.com/yarkukhtinprojectimages/logo.svg', class: 'logo' %>
            <span id="statement">
              <h1 id="header" class="wow bounce">I make motion graphics & animation.</h1>
              <a id="portfolio-btn" href="#portfolio" class="btn btn-default smoothScroll">WORK</a>
              <a id="contact-btn" href="#contact" class="btn btn-default smoothScroll">WHO</a>
            </span>
           </div>
        </div>
      </div>
    </section>
    <!-- navigation section -->
    <div class="navbar navbar-default navbar-static-top" role="navigation" style="height:71px;background:whitesmoke;">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon icon-bar"></span> <span class="icon icon-bar"></span> <span class="icon icon-bar"></span> </button>
          <a href="#" class="navbar-brand" style="margin-bottom:20px;">YarKukhtin</a></div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#portfolio" class="smoothScroll">WORK</a></li>
            <li><a href="#contact" class="smoothScroll">WHO</a></li>
          </ul>
        </div>
      </div>
    </div>

app/views/visitor/index.html.erb
<%= render 'header' %>

<!-- portfolio section -->
<div id="portfolio">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 title">
        <h2>Portfolio</h2>
        <hr>
      </div>

      <div class="col-md-12 col-sm-12"></div>
      <% @projects.each do |p| %>
      	<div class="col-md-3 col-sm-3 wow fadeIn" data-wow-delay="0.6s">
	      	<%= link_to(show_project_path(p)) do %>
	          <%= image_tag "#{p.base_image}", class: 'project-image' %>
	        <% end %>
	      </div>
      <% end %>
    </div>
  </div>
</div>

<!-- contact section -->
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 title">
        <h2>Contact Me</h2>
        <hr>
      </div>
      <div class="col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 contact-form wow fadeInUp" data-wow-delay="0.9s">
        <%= simple_form_for(:contact, url: contact_form_path, method: :put) do |f| %>
		  		<%= f.input :full_name, input_html: { class:"form-control" }, label: false, placeholder: 'Full Name' %>
		  		<%= f.input :email, input_html: { class:"form-control" }, label: false, placeholder: 'Email Address'  %>
		  		<%= f.input :body, as: :text, input_html: {rows: 5, cols: 20, class:"form-control"}, label: false, placeholder: 'Message'  %>

		  		<%= f.submit "Let's Chat", class:"form-control submit-btn" %>
		  	<% end %>
      </div>
    </div>
  </div>
</section>

<!-- google map section -->
<div class="google_map">
  <div id="map-canvas"></div>
</div>

<%= render 'footer' %>

app/views/visitor/show_project.html.erb
<!-- contact section -->
<section id="show-page">
  <div class="container">
  	<div class="row">
	  	<div class="col-lg-12">
	  		<h2><%= @project.name %></h2>
	  	</div>
  	</div>
    <div class="row">
	    <div class="col-lg-12">
	    	<%= image_tag "#{@project.base_image.url}", class: 'show-image' %>
	    </div>
    </div>
  </div>
</section>